# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(358, 700)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 14, 331, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loginBtn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setMouseTracking(False)
        self.loginBtn.setAutoFillBackground(False)
        self.loginBtn.setObjectName("loginBtn")
        self.gridLayout_2.addWidget(self.loginBtn, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.userName = QtWidgets.QLineEdit(self.layoutWidget)
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 0, 1, 1, 1)
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label2.setFont(font)
        self.label2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 200, 331, 461))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.snameTxt = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.snameTxt.setObjectName("snameTxt")
        self.gridLayout_3.addWidget(self.snameTxt, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 7, 0, 1, 1)
        self.ageTxt = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.ageTxt.setObjectName("ageTxt")
        self.gridLayout_3.addWidget(self.ageTxt, 7, 1, 1, 1)
        self.password2Txt = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.password2Txt.setObjectName("password2Txt")
        self.gridLayout_3.addWidget(self.password2Txt, 6, 1, 1, 1)
        self.passwordTxt = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.passwordTxt.setObjectName("passwordTxt")
        self.gridLayout_3.addWidget(self.passwordTxt, 5, 1, 1, 1)
        self.userNameTxt = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.userNameTxt.setObjectName("userNameTxt")
        self.gridLayout_3.addWidget(self.userNameTxt, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.nameTxt = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.nameTxt.setObjectName("nameTxt")
        self.gridLayout_3.addWidget(self.nameTxt, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.RegBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.RegBtn.setFont(font)
        self.RegBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.RegBtn.setAutoFillBackground(False)
        self.RegBtn.setObjectName("RegBtn")
        self.verticalLayout.addWidget(self.RegBtn)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.loginBtn.setText(_translate("LoginWindow", "Login"))
        self.label1.setText(_translate("LoginWindow", "Username :"))
        self.label2.setText(_translate("LoginWindow", "Password  :"))
        self.label_5.setText(_translate("LoginWindow", "Password :"))
        self.label_4.setText(_translate("LoginWindow", "Username :"))
        self.label_8.setText(_translate("LoginWindow", "Age :"))
        self.label_6.setText(_translate("LoginWindow", "Surname :"))
        self.label_3.setText(_translate("LoginWindow", "Name :"))
        self.label_7.setText(_translate("LoginWindow", "Password(again) :"))
        self.RegBtn.setText(_translate("LoginWindow", "Register"))
